// ============================================================
//  PadClaw — Bilingual Copy Versions (EN + 繁體中文)
//  3 versions × 2 languages = 6 complete copy sets
//  Add new versions by appending to VERSIONS array.
// ============================================================
const VERSIONS = [

// ═══════════════════════════════════════════════════════════
//  VERSION A — Category-First
// ═══════════════════════════════════════════════════════════
{
  id: 'a',
  label: { en: 'A — Category-First', zh: 'A — 類別定義' },
  description: {
    en: 'Defines PadClaw as a new product category. Declarative, confident, spec-backed. Best for tech-savvy backers and press coverage.',
    zh: '將 PadClaw 定義為全新產品類別。語氣自信、宣示性強、規格佐證。適合科技媒體與進階用戶。',
  },
  copy: {
    en: {
      title: 'PadClaw — The World\'s First Purpose-Built AI Agent Tablet',
      subtitle: 'Not a tablet with AI apps bolted on. A dedicated 10.1" device, purpose-built for always-on AI agents. Language learning, health tracking, daily planning — live and working the moment you turn it on. No prompts. No setup. No subscriptions for year one.',
      trust1: 'No Subscription for Year One',
      trust2: 'Your Data Stays On-Device',
      trust3: 'Full Android 14 — Install Any App',
      trust4: 'Ships Worldwide',
      s1_heading: 'A New Category of Device',
      s1_body: '<p>Every major AI company is building tools for power users — chat interfaces, developer APIs, enterprise platforms. <strong>Nobody is building for the other 90%.</strong> That\'s 4 billion smartphone users who have heard of AI but have no practical way to use it.</p><p>PadClaw is the first device designed from the ground up around <strong>AI agents</strong> — autonomous assistants that understand context, take initiative, and operate through purpose-built interfaces. Not a chatbot on a tablet. A tablet built because of AI. We tested prototypes with 120+ non-technical users across three countries. The result: 94% completed their first task within two minutes of unboxing.</p>',
      s2_heading: 'Why a Dedicated Device?',
      s2_body: '<p>We considered building an app. But apps compete with notifications, social media, and a hundred other distractions on your phone. PadClaw is a <strong>dedicated surface</strong> — a 10.1" tablet designed to sit on your kitchen counter, nightstand, or desk. Always on. Always focused on helping you.</p><p>Think of it less like a tablet and more like a <strong>digital family member</strong> — one that remembers your medication schedule, helps your kid practice Spanish, and tells you to grab an umbrella before you walk out the door.</p>',
      s2_features: '<li>Unbox. Connect Wi-Fi. Your agents are live in 60 seconds</li><li>Purpose-built AI agents with dedicated interfaces — not generic chatbots</li><li>Designed for non-technical users from the ground up</li><li>Full Android 14 — install any app from Google Play</li><li>Privacy-first architecture — sensitive data processed on-device, never uploaded without consent</li><li>Always-on display — your agents work even when you\'re not looking</li>',
      s3_heading: 'Launch Agents',
      s3_intro: 'Four agents ship with every PadClaw at launch. Each represents a high-frequency use case validated through extensive user research:',
      agent1_label: 'Language',
      agent1_title: 'Adaptive Language Tutor',
      agent1_desc: 'Real-time proficiency assessment with natural conversation drills. The agent adjusts difficulty dynamically, provides instant grammar corrections, and builds vocabulary through contextual immersion. Supports English, Spanish, Japanese, Korean, French, and more.',
      agent1_tags: '<span>Adaptive learning</span><span>Voice interaction</span><span>Multi-language</span>',
      agent2_label: 'Astrology',
      agent2_title: 'Personalized Astrology Engine',
      agent2_desc: 'Full natal chart generation from your birth data with real-time planetary transit tracking. Delivers personalized daily readings covering relationships, career timing, and personal growth — not generic horoscopes.',
      agent2_tags: '<span>Natal chart</span><span>Daily transits</span><span>Compatibility</span>',
      agent3_label: 'Weather',
      agent3_title: 'Context-Aware Weather Intelligence',
      agent3_desc: 'Fuses weather data with your calendar, commute patterns, and household routines. Doesn\'t just report temperature — tells you to bring an umbrella, skip the highway, or add a jacket for tonight\'s outdoor plans.',
      agent3_tags: '<span>Proactive alerts</span><span>Calendar-aware</span><span>Outfit guidance</span>',
      agent4_label: 'Health',
      agent4_title: 'Family Health Companion',
      agent4_desc: 'Multi-profile health tracking for every household member. Manages medication schedules, appointment reminders, and symptom logging. Includes a triage layer that evaluates severity and recommends when to see a doctor.',
      agent4_tags: '<span>Medication alerts</span><span>Symptom triage</span><span>Elder care</span>',
      s4_heading: 'Post-Launch Agent Roadmap',
      up1_label: 'Recipe', up1_title: 'Smart Recipe Assistant', up1_desc: 'Snap a photo of your fridge. The agent identifies ingredients and suggests meals you can make right now — with step-by-step instructions and nutritional breakdowns.',
      up2_label: 'Stories', up2_title: 'Interactive Storytime for Kids', up2_desc: 'AI-generated bedtime stories where your child picks the characters, setting, and plot twists. Every story is unique, age-appropriate, and narrated aloud.',
      up3_label: 'Finance', up3_title: 'Personal Finance Tracker', up3_desc: 'Log expenses by voice or photo. Auto-categorizes transactions and generates monthly spending reports with actionable savings insights.',
      up4_label: 'Fitness', up4_title: 'Adaptive Fitness Coach', up4_desc: 'Personalized training plans built around your body metrics and goals. Tracks progress, provides form guidance, and adjusts intensity as you improve.',
      s5_heading: 'What\'s in the Box',
      s5_body: '<p>Every PadClaw ships with everything you need to get started:</p><ul class="feature-list"><li>PadClaw AI Tablet (10.1" IPS, 128GB)</li><li>Protective case</li><li>USB-C charging cable + adapter</li><li>Magnetic desktop stand (Early Bird tier and above)</li><li>Quick start guide</li><li>1-year AI agent access — no subscription required for the first year</li></ul>',
      s6_heading: 'Technical Specifications',
      s7_heading: 'Why Trust Us',
      s7_body: '<p>PadClaw is built by a team based in Taipei, Taiwan — the same city that produces hardware for some of the world\'s largest tech companies.</p><p>Our track record in numbers:</p><ul class="feature-list"><li><strong>3 consumer hardware products</strong> shipped to market (combined 50,000+ units)</li><li><strong>4-year continuous relationship</strong> with our manufacturing partner — same factory, same engineering team</li><li><strong>200,000+ active users</strong> on AI platforms we\'ve built and operated</li><li><strong>$12M+ in hardware</strong> successfully manufactured and fulfilled</li><li>Full <strong>EVT → DVT → PVT</strong> validation cycle completed on previous products with zero recall incidents</li></ul><p>We are not asking you to fund a concept sketch. Our working prototype already exists. The factory already has our specifications.</p>',
      s8_heading: 'Project Timeline',
      s9_heading: 'Shipping & Fulfillment',
      s9_body: '<p><strong>US backers ship first.</strong> We are partnering with a US-based fulfillment center to ensure domestic backers receive their units with the shortest possible lead time.</p><p>International shipping is available worldwide. Shipping costs will be collected separately via a post-campaign survey (BackerKit) — not included in your pledge amount. Customs duties and import taxes are the responsibility of the backer, as is standard for international Kickstarter campaigns.</p><p>We will publish region-specific shipping cost estimates before the campaign ends so you can make an informed decision.</p>',
      s10_heading: 'Risks and Challenges',
      s10_body: '<p>Hardware is unpredictable. Components get delayed. Molds need revision. Firmware bugs surface at the worst time. We will not pretend otherwise.</p><p>Our mitigation strategy: dual-sourcing critical components, maintaining a 6-week schedule buffer, and manufacturing at a facility with whom we have a 4-year working relationship. Backers will receive <strong>engineering-level updates</strong> — real photos, real numbers, revised timelines when necessary. No marketing fluff.</p>',
      faq1_q: 'Is there a subscription fee for the AI agents?', faq1_a: 'Every PadClaw includes one full year of AI agent access at no extra cost. After year one, a modest subscription will apply to cover ongoing cloud AI costs. Pricing will be announced before units ship — no surprises.',
      faq2_q: 'Where does my personal data go?', faq2_a: 'PadClaw uses a privacy-first architecture. Sensitive data is processed on-device whenever possible. Nothing is uploaded to the cloud without your explicit consent. All conversation history can be deleted at any time.',
      faq3_q: 'Can I install apps from Google Play?', faq3_a: 'Yes. PadClaw runs full Android 14 with Google Play Services. Install and use any Android app alongside PadClaw\'s built-in agents.',
      faq4_q: 'Do you ship internationally?', faq4_a: 'Yes. We ship worldwide. Shipping costs are collected separately after the campaign via BackerKit survey. US backers get priority fulfillment.',
      faq5_q: 'Will there be more agents after launch?', faq5_a: 'Absolutely. We have a growing roadmap of new agents. Kickstarter backers receive all new agents as free updates during their included subscription period.',
      faq6_q: 'What if production is delayed?', faq6_a: 'We have built a 6-week buffer into our timeline and dual-source critical components. If delays occur, you will hear from us directly — with specifics, factory photos, and revised dates. No vague reassurances.',
      r1_title: 'Founding Supporter', r1_desc: 'Join the PadClaw founding community. Receive prioritized backer updates with engineering-level detail and be recognized as a founding supporter when the product ships.',
      r2_title: 'Super Early Bird — PadClaw', r2_desc: 'The absolute lowest price PadClaw will ever be offered — campaign or retail, guaranteed. Secure yours at 40% off the $999 retail price. Includes tablet, case, cable, and one full year of AI agent access. Only 200 available. Once they\'re gone, this price is gone forever.',
      r3_title: 'Early Bird — PadClaw + Stand', r3_desc: 'Lock in PadClaw at 30% off retail ($999). Includes everything in Super Early Bird plus the magnetic desktop stand for countertop deployment. This is the most popular tier for a reason — it\'s the complete home setup at a price that won\'t come back.',
      r4_title: 'Kickstarter Special — PadClaw + Stand', r4_desc: 'Still 20% below the $999 retail price. Full hardware package with magnetic stand and one year of AI agent access included.',
      r5_title: 'Duo Pack — Two PadClaws', r5_desc: 'Two complete PadClaw setups — one for you, one for your parents. Each unit operates independently with its own agent profiles and one-year subscription.',
      r6_title: 'Enterprise — Five PadClaws', r6_desc: 'Designed for classrooms, clinics, and senior living facilities. Five units with all accessories, priority support, two-year AI access, and custom agent configuration options.',
    },
    zh: {
      title: 'PadClaw — 全球首款專為 AI Agent 而生的平板',
      subtitle: '不是裝了 AI 應用的平板。是一台專為 always-on AI 代理人而生的 10.1 吋 Android 裝置 — 語言學習、健康追蹤、日常規劃，開機 60 秒即可使用。不用 prompt、不用設定、首年免訂閱。',
      trust1: '首年免訂閱費',
      trust2: '資料留在裝置上',
      trust3: '完整 Android 14 — 自由安裝 APP',
      trust4: '全球配送',
      s1_heading: '一個全新的裝置類別',
      s1_body: '<p>所有 AI 大廠都在為進階用戶打造工具 — 聊天介面、開發者 API、企業平台。<strong>沒有人為另外 90% 的人設計。</strong>那是 40 億拿著手機、聽過 AI 卻不知道怎麼用的人。</p><p>PadClaw 是第一台從底層就圍繞 <strong>AI 代理人</strong> 設計的裝置 — 自主運作的智慧助手，理解上下文、主動行動、透過專屬介面操作。不是平板上裝個聊天機器人，而是因為 AI 才誕生的平板。我們在三個國家測試了 120 位以上的非技術用戶，結果：94% 的人在開箱兩分鐘內完成第一個任務。</p>',
      s2_heading: '為什麼需要一台專屬裝置？',
      s2_body: '<p>我們考慮過做 APP。但 APP 活在你已經被通知淹沒的手機裡。PadClaw 是一個<strong>專屬的介面</strong> — 一台 10.1 吋的平板，設計來放在廚房檯面、床頭櫃或書桌上。永遠待命，永遠專注在幫助你。</p><p>與其說它是一台平板，不如說它更像一個<strong>數位家庭成員</strong> — 記得你的用藥時間、幫孩子練習外語、出門前提醒你帶傘。</p>',
      s2_features: '<li>拆箱、連 Wi-Fi、代理人 60 秒內上線</li><li>專屬 AI 代理人配專屬介面 — 不是通用聊天機器人</li><li>從零開始為非技術用戶設計</li><li>完整 Android 14 — 自由安裝 Google Play 上的任何應用</li><li>隱私優先架構 — 敏感資料在裝置端處理，未經同意絕不上傳</li><li>Always-on 螢幕 — 代理人在你沒看的時候也在運作</li>',
      s3_heading: '首發 AI 代理人',
      s3_intro: '每台 PadClaw 出廠即搭載四款代理人，皆經過深度用戶研究驗證：',
      agent1_label: '語言',
      agent1_title: '自適應語言教練',
      agent1_desc: '即時評估你的程度，透過自然對話練習動態調整難度。提供即時文法糾正，以情境沉浸式學習取代死記硬背。支援英語、西語、日語、韓語、法語等多國語言。',
      agent1_tags: '<span>自適應學習</span><span>語音互動</span><span>多國語言</span>',
      agent2_label: '星座',
      agent2_title: '個人化星座分析引擎',
      agent2_desc: '根據你的出生資料建立完整本命盤，即時追蹤行星流年。提供每日個人化解讀 — 感情、事業時機、個人成長，不是籠統的星座運勢。',
      agent2_tags: '<span>本命盤</span><span>每日流年</span><span>配對分析</span>',
      agent3_label: '天氣',
      agent3_title: '情境感知天氣智能',
      agent3_desc: '整合天氣數據、你的行事曆、通勤路線和家庭作息。不只報溫度 — 告訴你該帶傘、避開哪條路、晚上的戶外活動要不要多帶件外套。',
      agent3_tags: '<span>主動提醒</span><span>行事曆整合</span><span>穿搭建議</span>',
      agent4_label: '健康',
      agent4_title: '家庭健康夥伴',
      agent4_desc: '多人健康追蹤，管理每位家庭成員的用藥排程、回診提醒和症狀紀錄。內建分級評估層，判斷嚴重程度並建議是否就醫。',
      agent4_tags: '<span>用藥提醒</span><span>症狀分級</span><span>長輩照護</span>',
      s4_heading: '上市後代理人擴充計畫',
      up1_label: '食譜', up1_title: '智慧食譜助手', up1_desc: '拍一張冰箱照片，代理人辨識食材並推薦你現在就能做的料理 — 附上步驟說明和營養分析。',
      up2_label: '故事', up2_title: '互動式兒童故事', up2_desc: '孩子選擇角色、場景和劇情走向，AI 即時產生獨一無二的床邊故事，並朗讀出聲。',
      up3_label: '理財', up3_title: '個人理財追蹤', up3_desc: '用語音或拍照記帳，自動分類交易，每月產出花費報告與具體省錢建議。',
      up4_label: '健身', up4_title: '自適應健身教練', up4_desc: '根據身體數據和目標制定訓練計畫，追蹤進度、提供姿勢指導，隨你進步自動調整強度。',
      s5_heading: '盒裝內容',
      s5_body: '<p>每台 PadClaw 隨附所有必要配件：</p><ul class="feature-list"><li>PadClaw AI 平板（10.1 吋 IPS、128GB）</li><li>保護殼</li><li>USB-C 充電線 + 充電器</li><li>磁吸立架（早鳥方案以上）</li><li>快速入門指南</li><li>首年 AI 代理人使用權 — 第一年免訂閱費</li></ul>',
      s6_heading: '硬體規格',
      s7_heading: '為什麼值得信任',
      s7_body: '<p>PadClaw 團隊位於台灣台北 — 全球頂尖科技硬體的生產重鎮。</p><p>我們的實績數據：</p><ul class="feature-list"><li><strong>3 款消費性硬體產品</strong>已出貨（累計 50,000+ 台，零召回）</li><li>與製造夥伴維持 <strong>4 年不間斷合作</strong> — 同一間工廠、同一組工程團隊</li><li><strong>200,000+ 活躍用戶</strong>使用我們建置並營運的 AI 平台</li><li>累計 <strong>超過 3,600 萬美元</strong>硬體成功生產與出貨</li><li>前代產品完成完整 <strong>EVT → DVT → PVT</strong> 驗證流程，零召回事件</li></ul><p>我們不是請你贊助一張概念圖。PadClaw 的工作原型已經存在。工廠已經拿到我們的規格。</p>',
      s8_heading: '專案時程',
      s9_heading: '出貨與物流',
      s9_body: '<p><strong>美國贊助者優先出貨。</strong>我們與美國在地物流中心合作，確保美國國內贊助者以最短時間收到裝置。</p><p>國際配送覆蓋全球。運費將於募資結束後透過問卷（BackerKit）另行收取，不含在贊助金額內。關稅與進口稅依各國規定由贊助者自行負擔，這是國際 Kickstarter 的標準做法。</p><p>我們會在募資結束前公布各地區的運費預估，讓你做出充分知情的決定。</p>',
      s10_heading: '風險與挑戰',
      s10_body: '<p>硬體開發充滿變數。零件延遲、模具修正、韌體除錯 — 我們不會假裝這些不存在。</p><p>我們的因應策略：關鍵零件雙源採購、時程預留 6 週緩衝、在合作 4 年的工廠量產。贊助者會收到<strong>工程等級的更新</strong> — 真實照片、真實數據、必要時的修正時程。不會有行銷包裝式的空話。</p>',
      faq1_q: 'AI 代理人需要訂閱費嗎？', faq1_a: '每台 PadClaw 含首年 AI 代理人使用權，無額外費用。第一年後將收取合理訂閱費以支應雲端 AI 成本。定價會在出貨前公布 — 不會有意外。',
      faq2_q: '我的個人資料會去哪裡？', faq2_a: 'PadClaw 採隱私優先架構。敏感資料盡可能在裝置端處理，未經你明確同意不會上傳雲端。所有對話紀錄可隨時刪除。',
      faq3_q: '可以安裝 Google Play 的 APP 嗎？', faq3_a: '可以。PadClaw 搭載完整 Android 14 與 Google Play 服務，可自由安裝任何 Android 應用。',
      faq4_q: '可以寄到海外嗎？', faq4_a: '可以，全球配送。運費於募資結束後透過 BackerKit 問卷另行收取。美國贊助者優先出貨。',
      faq5_q: '之後會有更多代理人嗎？', faq5_a: '當然。我們有持續擴充的代理人路線圖，Kickstarter 贊助者在訂閱期間內可免費取得所有新代理人。',
      faq6_q: '如果生產延遲怎麼辦？', faq6_a: '我們在時程中預留了 6 週緩衝，並對關鍵零件採雙源採購。若發生延遲，我們會直接告訴你 — 附上具體說明、工廠照片和修正後的日期。不會有含糊的安慰。',
      r1_title: '創始支持者', r1_desc: '加入 PadClaw 創始社群。獲得工程等級的優先專案更新，並在產品出貨時被列為創始支持者。',
      r2_title: '超級早鳥 — PadClaw', r2_desc: 'PadClaw 史上最低價 — 不論募資或零售，保證不再更低。以零售價 $999 的 6 折鎖定名額。含平板、保護殼、充電線與首年 AI 使用權。限量 200 組，售完即止。',
      r3_title: '早鳥 — PadClaw + 立架', r3_desc: '以零售價 $999 的 7 折取得 PadClaw。包含超級早鳥的全部內容，再加上磁吸立架。這是最多人選擇的方案 — 完整的家用配置，這個價格不會再來。',
      r4_title: 'Kickstarter 限定 — PadClaw + 立架', r4_desc: '仍比 $999 零售價低 20%。完整硬體套裝含磁吸立架與首年 AI 代理人使用權。',
      r5_title: '雙人組 — 兩台 PadClaw', r5_desc: '兩套完整 PadClaw — 一台給自己、一台給爸媽。每台獨立運作，各有自己的代理人設定與一年訂閱。',
      r6_title: '企業方案 — 五台 PadClaw', r6_desc: '適合教室、診所與長照機構。五台裝置含所有配件、優先客服、兩年 AI 使用權，以及客製化代理人設定。',
    },
  },
},

// ═══════════════════════════════════════════════════════════
//  VERSION B — Trust-First
// ═══════════════════════════════════════════════════════════
{
  id: 'b',
  label: { en: 'B — Trust-First', zh: 'B — 信任堆疊' },
  description: {
    en: 'Leads with proof, anti-friction, and risk reversal. Pragmatic, transparent, no-BS. Best for skeptical backers who need reassurance before committing $699.',
    zh: '以證據、降低摩擦與風險反轉開場。務實、透明、不說廢話。適合需要在出手 $699 前被說服的謹慎贊助者。',
  },
  copy: {
    en: {
      title: 'PadClaw — AI That Works The Moment You Turn It On',
      subtitle: 'No subscription traps. No data harvesting. No prompt engineering. A purpose-built Android tablet with always-on AI agents designed for real people — plug in, connect to Wi-Fi, and your assistants are live in 60 seconds.',
      trust1: 'First Year Included — No Hidden Fees',
      trust2: 'Privacy-First — Data Stays Local',
      trust3: 'Full Android 14 — Not a Locked Ecosystem',
      trust4: 'US Fulfillment — Ships Fast',
      s1_heading: 'Let\'s Be Direct About What This Is',
      s1_body: '<p>PadClaw is a 10.1-inch Android tablet with a custom launcher and a set of <strong>pre-built AI agents</strong> that are ready to use the moment you power it on. No accounts to create. No prompts to write. No AI expertise required. Plug in, connect to Wi-Fi, and your first agent is live in under 60 seconds.</p><p>It runs full Android 14, so you can still install Netflix, YouTube, Kindle — anything from Google Play. But the core experience is the agents: always-on intelligent assistants designed around specific daily tasks that most people actually need help with.</p><p><strong>Think of it as a purpose-built device for AI</strong> — the way a Kindle is purpose-built for reading. You can use a phone to read books, but a dedicated device changes the experience entirely.</p>',
      s2_heading: 'The Stuff You\'re Probably Wondering',
      s2_body: '<p><strong>"Is there a monthly fee?"</strong> — No. The first full year of AI agent access is included with every unit. After year one, there will be a subscription to cover cloud costs. We will announce pricing before any unit ships.</p><p><strong>"Where does my data go?"</strong> — Sensitive data is processed on-device. Your conversations, health logs, and personal preferences stay on your tablet. Nothing leaves without explicit consent. You own your data — always.</p><p><strong>"Is this just an Android tablet with ChatGPT?"</strong> — No. ChatGPT is a blank canvas that waits for you to know what to ask. PadClaw\'s agents are purpose-built tools with dedicated interfaces, pre-loaded context, and proactive behavior. You don\'t type prompts. You interact with assistants that already know their job.</p>',
      s2_features: '<li>One-year AI access included — no surprise charges, no hidden subscription traps</li><li>On-device data processing — your conversations stay on your tablet, period</li><li>Full Android — not a locked-down proprietary ecosystem. You own the device.</li><li>Purpose-built hardware and software — not vaporware, not a concept render</li><li>Transparent shipping — costs published before campaign ends</li><li>60-second setup — plug in, connect Wi-Fi, agents are live</li>',
      s3_heading: 'What the Agents Actually Do',
      s3_intro: 'Four agents come pre-installed. Here is exactly what each one does:',
      agent1_label: 'Language',
      agent1_title: 'Language Learning Agent',
      agent1_desc: 'Conducts spoken conversations at your level. Corrects grammar in real time. Adjusts difficulty as you improve. Supports English, Spanish, Japanese, Korean, French, and more. Fifteen minutes a day is enough to build a real habit.',
      agent1_tags: '<span>Spoken practice</span><span>Real-time feedback</span><span>Adaptive level</span>',
      agent2_label: 'Astrology',
      agent2_title: 'Astrology & Horoscope Agent',
      agent2_desc: 'You enter your birth data once. The agent generates your natal chart and delivers daily readings based on actual planetary transits — not generic horoscope filler. Covers relationships, career, finances, and personal energy.',
      agent2_tags: '<span>Your natal chart</span><span>Real transits</span><span>Daily reading</span>',
      agent3_label: 'Weather',
      agent3_title: 'Weather + Daily Prep Agent',
      agent3_desc: 'Connects to your calendar. Knows your commute. Tells you what to wear, whether to bring an umbrella, and warns about anything that might disrupt your day. Proactive — it alerts you before you ask.',
      agent3_tags: '<span>Calendar sync</span><span>Proactive alerts</span><span>Practical advice</span>',
      agent4_label: 'Health',
      agent4_title: 'Family Health Tracker',
      agent4_desc: 'Tracks medication schedules, doctor appointments, and symptoms for every person in your household. Describe how you feel in plain language — the agent evaluates severity and tells you if you should see a doctor.',
      agent4_tags: '<span>Whole-family tracking</span><span>Med reminders</span><span>Symptom check</span>',
      s4_heading: 'What\'s Coming After Launch',
      up1_label: 'Recipe', up1_title: 'Fridge-to-Table Recipe Agent', up1_desc: 'Photograph your ingredients. Get three meals you can cook right now with what you already have, plus nutritional info.',
      up2_label: 'Stories', up2_title: 'Bedtime Story Generator', up2_desc: 'Your child picks characters and plot direction. The agent produces a unique, age-appropriate story and narrates it aloud. Different every night.',
      up3_label: 'Finance', up3_title: 'Expense Tracking Agent', up3_desc: 'Log spending by voice or camera. Auto-categorized. Monthly reports with trends and savings opportunities. No spreadsheets required.',
      up4_label: 'Fitness', up4_title: 'Workout Planning Agent', up4_desc: 'Builds training programs based on your fitness level and goals. Adjusts as you progress. Provides form cues and rest-day scheduling.',
      s5_heading: 'What\'s in the Box — No Surprises',
      s5_body: '<p>We are listing exactly what you receive so there is no ambiguity:</p><ul class="feature-list"><li>PadClaw AI Tablet — 10.1" IPS display, 128GB storage, Android 14</li><li>Protective case</li><li>USB-C charging cable + wall adapter</li><li>Magnetic desktop stand (Early Bird and above)</li><li>Printed quick start guide</li><li>1-year AI agent subscription — activated on first boot</li></ul><p>That is everything. No hidden accessories sold separately. No "premium tier" unlock.</p>',
      s6_heading: 'Technical Specifications',
      s7_heading: 'Who We Are and Why We Can Deliver',
      s7_body: '<p>We are a hardware and software team based in Taipei, Taiwan. This is not our first product. Here are the facts:</p><ul class="feature-list"><li>3 consumer electronics products shipped (50,000+ units combined, zero recalls)</li><li>4-year continuous manufacturing relationship — same factory, same line</li><li>$12M+ in hardware successfully produced and fulfilled globally</li><li>200,000+ active users on AI platforms we built and maintain</li><li>Working PadClaw prototype exists today — this is not a concept render</li></ul><p>We are not asking you to trust a pitch deck. We are asking you to trust a team that has done this before, working with a factory that already has our BOM and tooling specifications on file.</p>',
      s8_heading: 'Timeline',
      s9_heading: 'How Shipping Works',
      s9_body: '<p>We are being upfront about this because shipping surprises kill trust:</p><ul class="feature-list"><li><strong>Shipping is NOT included</strong> in your pledge. It will be collected separately via BackerKit survey after the campaign.</li><li><strong>US backers ship first</strong> via our domestic fulfillment partner.</li><li><strong>International shipping</strong> is available worldwide. We will publish cost estimates by region before the campaign ends.</li><li><strong>Customs and import duties</strong> are the backer\'s responsibility, per standard international Kickstarter practice.</li></ul>',
      s10_heading: 'Our Honest Take on Risks',
      s10_body: '<p>Every hardware Kickstarter carries risk. Here is where ours stands:</p><p><strong>Supply chain:</strong> We dual-source all critical components and have backup suppliers identified. <strong>Timeline:</strong> We\'ve built a 6-week buffer into our schedule. <strong>Manufacturing:</strong> We produce at a facility we\'ve worked with for 4 years — no new factory onboarding risk.</p><p>If something goes wrong, you will hear about it from us directly — with factory photos, component details, and revised dates. We do not do vague "we\'re working on it" updates.</p>',
      faq1_q: 'Do I have to pay a monthly subscription?', faq1_a: 'Not for the first year. Every PadClaw includes 12 months of AI agent access. After that, a subscription will be required for cloud-based features. Pricing will be announced before shipping begins.',
      faq2_q: 'Is my data being sold or sent to third parties?', faq2_a: 'No. PadClaw processes sensitive data on-device. Cloud processing is opt-in only, and we do not sell, share, or monetize user data. Period.',
      faq3_q: 'Is this a locked-down system or full Android?', faq3_a: 'Full Android 14 with Google Play Services. PadClaw has a custom launcher for the agent experience, but you can switch to the standard Android home screen and install anything.',
      faq4_q: 'How much is shipping?', faq4_a: 'Shipping is collected post-campaign via BackerKit. We will publish region-specific estimates before the campaign closes. US domestic shipping will be competitive with standard e-commerce rates.',
      faq5_q: 'What happens if the project is delayed?', faq5_a: 'We have a 6-week buffer in our timeline and dual-source critical components. If delays happen, we publish detailed engineering updates with photos and revised timelines — not vague reassurances.',
      faq6_q: 'Can I get a refund if I change my mind?', faq6_a: 'Per Kickstarter policy, pledges can be adjusted or cancelled at any time before the campaign ends. After the campaign closes, refund policies will be detailed in our BackerKit survey.',
      r1_title: 'Show of Support', r1_desc: 'Back the vision. You receive exclusive backer-only updates with engineering details and team notes throughout the development process.',
      r2_title: 'Super Early Bird — Best Price Ever', r2_desc: 'PadClaw at 40% off the $999 retail price. This is the lowest price it will ever be offered — campaign or retail. Guaranteed. Only 200 slots. Includes tablet, case, cable, and 12 months of AI access. There is no cheaper way to get PadClaw. Full stop.',
      r3_title: 'Early Bird — Full Kit', r3_desc: '30% off retail. Everything in Super Early Bird plus the magnetic desktop stand. The complete home deployment kit at a price that disappears when these 500 slots fill up. This is our most-backed tier.',
      r4_title: 'Kickstarter Price — Full Kit', r4_desc: 'Still $200 below the $999 retail price. Full hardware kit with stand and one year of AI access. No lock-in, no hidden costs.',
      r5_title: 'Two-Pack — Share With Family', r5_desc: 'Two PadClaw units with independent profiles and subscriptions. Save $699 versus buying two at retail. Each unit works standalone.',
      r6_title: 'Team Deployment — Five Units', r6_desc: 'For organizations. Five PadClaws with fleet support, two-year AI access per device, dedicated support channel, and customizable agent configurations.',
    },
    zh: {
      title: 'PadClaw — 開機就能用的 AI 平板',
      subtitle: '沒有訂閱陷阱。沒有資料蒐集。不需要學 prompt。一台專為 AI 代理人而生的 Android 平板，插電、連 Wi-Fi，60 秒內助手即刻上線。',
      trust1: '首年使用權含在內 — 沒有隱藏費用',
      trust2: '隱私優先 — 資料留在本機',
      trust3: '完整 Android 14 — 不是封閉系統',
      trust4: '美國優先出貨',
      s1_heading: '直接告訴你這是什麼',
      s1_body: '<p>PadClaw 是一台 10.1 吋的 Android 平板，搭載客製化桌面和一組<strong>預裝 AI 代理人</strong>，開機就能用。不需要建帳號、不需要寫 prompt、不需要任何 AI 知識。</p><p>它跑的是完整 Android 14，所以你照樣可以裝 Netflix、YouTube、Kindle — Google Play 上什麼都能裝。但核心體驗是代理人：針對日常真實需求設計的智慧助手。</p>',
      s2_heading: '你大概在想的幾件事',
      s2_body: '<p><strong>「要月費嗎？」</strong> — 不用。每台 PadClaw 含首年 AI 代理人使用權。第一年後會有訂閱費以支應雲端 AI 成本。定價會在出貨前公布。</p><p><strong>「資料去哪裡？」</strong> — 敏感資料在裝置端處理。未經你同意不會離開平板。對話紀錄可隨時刪除。</p><p><strong>「這只是裝了 ChatGPT 的平板嗎？」</strong> — 不是。每個代理人有專屬介面、預載情境和主動行為。你不是在打字下指令，而是在使用專門設計的工具。</p>',
      s2_features: '<li>首年 AI 使用權含在內 — 不會有意外收費，沒有隱藏訂閱陷阱</li><li>裝置端資料處理 — 你的對話留在平板上，就這樣</li><li>完整 Android — 不是封閉的專有生態系。裝置是你的。</li><li>專為 AI 而生的硬軟體 — 不是畫餅，不是概念渲染圖</li><li>運費透明 — 募資結束前公布各地運費</li><li>60 秒設定 — 插電、連 Wi-Fi、代理人即刻上線</li>',
      s3_heading: '代理人到底做什麼',
      s3_intro: '四款代理人預裝出貨。以下是每個代理人的具體功能：',
      agent1_label: '語言',
      agent1_title: '語言學習代理人',
      agent1_desc: '用你的程度進行口說對話，即時糾正文法，隨你進步調整難度。支援英語、西語、日語、韓語、法語等。每天 15 分鐘就夠養成習慣。',
      agent1_tags: '<span>口說練習</span><span>即時回饋</span><span>自適應程度</span>',
      agent2_label: '星座',
      agent2_title: '星座運勢代理人',
      agent2_desc: '輸入一次出生資料，代理人產生你的本命盤，根據實際行星流年提供每日解讀 — 不是套版星座運勢。涵蓋感情、事業、財務和個人能量。',
      agent2_tags: '<span>你的本命盤</span><span>真實流年</span><span>每日解讀</span>',
      agent3_label: '天氣',
      agent3_title: '天氣 + 出門準備代理人',
      agent3_desc: '連結你的行事曆，知道你的通勤路線。告訴你穿什麼、要不要帶傘、今天有什麼可能影響行程的事。主動提醒 — 不用你開口問。',
      agent3_tags: '<span>行事曆同步</span><span>主動提醒</span><span>實用建議</span>',
      agent4_label: '健康',
      agent4_title: '家庭健康追蹤',
      agent4_desc: '追蹤每位家人的用藥時間、回診排程和症狀紀錄。用白話描述你的感覺 — 代理人會評估嚴重程度，告訴你是否該看醫生。',
      agent4_tags: '<span>全家追蹤</span><span>用藥提醒</span><span>症狀檢查</span>',
      s4_heading: '上市後還會推出什麼',
      up1_label: '食譜', up1_title: '冰箱到餐桌食譜代理人', up1_desc: '拍你的食材，馬上得到三道你現在就能煮的菜，附營養資訊。',
      up2_label: '故事', up2_title: '睡前故事產生器', up2_desc: '孩子選角色和劇情方向，代理人產出獨一無二、適齡的故事並朗讀。每晚都不一樣。',
      up3_label: '理財', up3_title: '支出追蹤代理人', up3_desc: '用語音或拍照記帳，自動分類。月報含趨勢和省錢機會。不需要試算表。',
      up4_label: '健身', up4_title: '訓練計畫代理人', up4_desc: '根據你的體能和目標制定訓練計畫，隨你進步調整，提供動作提示和休息日安排。',
      s5_heading: '盒裝內容 — 沒有意外',
      s5_body: '<p>我們列出你會收到的每一樣東西，不留模糊空間：</p><ul class="feature-list"><li>PadClaw AI 平板 — 10.1 吋 IPS 螢幕、128GB、Android 14</li><li>保護殼</li><li>USB-C 充電線 + 充電器</li><li>磁吸立架（早鳥方案以上）</li><li>紙本快速入門指南</li><li>首年 AI 代理人訂閱 — 首次開機即啟用</li></ul><p>就這些。沒有另售配件，沒有「進階版」解鎖。</p>',
      s6_heading: '硬體規格',
      s7_heading: '我們是誰、為什麼能交付',
      s7_body: '<p>我們是台北的硬軟體團隊。這不是我們的第一個產品。以下是事實：</p><ul class="feature-list"><li>3 款消費性電子產品已出貨（累計 50,000+ 台，零召回）</li><li>與同一間工廠維持 4 年不間斷合作</li><li>累計超過 3,600 萬美元硬體成功生產與全球出貨</li><li>200,000+ 活躍用戶使用我們建置的 AI 平台</li><li>PadClaw 工作原型已經存在 — 這不是概念渲染圖</li></ul><p>我們請你信任的不是簡報，而是一支做過的團隊，合作的工廠已經拿到我們的 BOM 和模具規格。</p>',
      s8_heading: '時程',
      s9_heading: '出貨方式說明',
      s9_body: '<p>我們提前說清楚，因為出貨意外最傷信任：</p><ul class="feature-list"><li><strong>運費不含在贊助金額內</strong>，會在募資結束後透過 BackerKit 問卷另行收取。</li><li><strong>美國贊助者優先出貨</strong>，透過美國本地物流夥伴。</li><li><strong>國際配送</strong>覆蓋全球，我們會在募資結束前公布各地區運費預估。</li><li><strong>關稅與進口稅</strong>由贊助者自行負擔，這是國際 Kickstarter 的標準做法。</li></ul>',
      s10_heading: '我們對風險的誠實看法',
      s10_body: '<p>每個硬體 Kickstarter 都有風險。以下是我們的現況：</p><p><strong>供應鏈：</strong>所有關鍵零件皆雙源採購，備援供應商已確認。<strong>時程：</strong>排程中預留 6 週緩衝。<strong>製造：</strong>在合作 4 年的工廠生產 — 沒有新工廠磨合風險。</p><p>如果出問題，我們會直接告訴你 — 附上工廠照片、零件細節和修正日期。我們不會做「正在努力中」這種含糊更新。</p>',
      faq1_q: '需要付月費嗎？', faq1_a: '第一年不用。每台 PadClaw 含 12 個月 AI 代理人使用權。之後雲端功能需要訂閱。定價會在出貨前公布。',
      faq2_q: '我的資料會被賣掉或給第三方嗎？', faq2_a: '不會。PadClaw 在裝置端處理敏感資料。雲端處理是選擇性開啟的，我們不販售、不分享、不變現用戶資料。句號。',
      faq3_q: '這是封閉系統還是完整 Android？', faq3_a: '完整 Android 14，含 Google Play 服務。PadClaw 有客製化桌面呈現代理人體驗，但你可以切回標準 Android 主畫面，安裝任何應用。',
      faq4_q: '運費多少？', faq4_a: '運費在募資結束後透過 BackerKit 收取。我們會在募資關閉前公布各地區預估費用。美國國內運費會與一般電商水準相當。',
      faq5_q: '如果生產延遲怎麼辦？', faq5_a: '時程預留 6 週緩衝，關鍵零件雙源採購。若延遲發生，我們會發出詳細工程更新 — 附照片和修正時程 — 不會有含糊安慰。',
      faq6_q: '改變主意可以退款嗎？', faq6_a: '依 Kickstarter 規定，募資期間內可隨時調整或取消贊助。募資結束後的退款政策會在 BackerKit 問卷中說明。',
      r1_title: '精神支持', r1_desc: '支持這個願景。獲得附帶工程細節與團隊筆記的贊助者專屬更新。',
      r2_title: '超級早鳥 — 史上最低價', r2_desc: '以零售價 $999 的 6 折取得 PadClaw。這是它有史以來最低的價格 — 不論募資或零售。含平板、保護殼、充電線與 12 個月 AI 使用權。',
      r3_title: '早鳥 — 完整套裝', r3_desc: '零售價 7 折。包含超級早鳥的全部內容，再加磁吸立架。適合放在廚房檯面或書桌上的完整配置。',
      r4_title: 'Kickstarter 價 — 完整套裝', r4_desc: '仍比 $999 零售價低 $200。完整硬體套裝含立架與首年 AI 使用權。不綁約、不隱藏費用。',
      r5_title: '雙人組 — 家人共享', r5_desc: '兩台 PadClaw，獨立設定與訂閱。比零售買兩台省 $699。每台獨立運作。',
      r6_title: '團隊部署 — 五台', r6_desc: '適合組織機構。五台 PadClaw 含車隊管理支援、每台兩年 AI 使用權、專屬客服通道與可自訂的代理人設定。',
    },
  },
},

// ═══════════════════════════════════════════════════════════
//  VERSION C — Outcome-Driven
// ═══════════════════════════════════════════════════════════
{
  id: 'c',
  label: { en: 'C — Outcome-Driven', zh: 'C — 情境導向' },
  description: {
    en: 'Leads with life transformation and relatable scenarios. Warm, personal, family-oriented. Best for mainstream consumers, gift buyers, and backers who connect through stories.',
    zh: '以生活場景和情感共鳴開場。溫暖、個人化、以家庭為核心。適合一般消費者、送禮族和透過故事連結的贊助者。',
  },
  copy: {
    en: {
      title: 'PadClaw — Less Switching. More Living.',
      subtitle: 'A calm, always-on AI tablet that brings together language practice, health reminders, daily briefings, and family coordination — purpose-built for the kitchen counter, the nightstand, and every moment in between.',
      trust1: 'Year One Included — No Surprise Fees',
      trust2: 'Your Conversations Stay Private',
      trust3: 'Also a Full Android Tablet',
      trust4: 'Free US Shipping for VIP Backers',
      s1_heading: 'What If Your Tablet Already Knew What to Do?',
      s1_body: '<p>Imagine waking up and glancing at the tablet on your nightstand. It already knows it\'s going to rain on your commute. It reminds you to take your vitamins. Your daughter used it last night to practice her French homework — and actually <em>enjoyed</em> it.</p><p>That\'s PadClaw. Not another gadget you have to figure out. Not another app buried under 47 notifications. It\'s a <strong>dedicated AI companion</strong> for your household — pre-loaded with smart assistants designed around the things your family actually needs help with, every single day.</p><p>We tested PadClaw with 120+ families. The most common reaction from parents: <strong>"Why didn\'t this exist before?"</strong></p>',
      s2_heading: 'Why Not Just Use Your Phone?',
      s2_body: '<p>Because your phone is already doing too much. Between texts, social media, work emails, and doom-scrolling, there\'s no room left for something that genuinely helps.</p><p>PadClaw lives on your counter, your desk, your coffee table — <strong>a calm, focused surface</strong> that\'s always ready when you need it. It\'s the difference between a kitchen timer buried in your phone and a beautiful clock on the wall. Presence matters. Dedicated purpose matters.</p>',
      s2_features: '<li>Unbox it, connect to Wi-Fi, and your assistants are live in 60 seconds</li><li>Every assistant is designed for people who have never used AI before</li><li>The whole family can use it — no separate accounts or logins needed</li><li>It\'s still a full Android tablet — Netflix, YouTube, Kindle all work</li><li>Your personal data stays on the device — you own it, not us</li><li>Always-on display means your agents are ready before you even ask</li>',
      s3_heading: 'Built-in Assistants for Real Life',
      s3_intro: 'Every PadClaw comes pre-loaded with AI assistants designed around everyday moments:',
      agent1_label: 'Learn',
      agent1_title: 'Your Personal Language Partner',
      agent1_desc: 'Practicing a new language shouldn\'t feel like homework. PadClaw\'s language assistant has real conversations with you, corrects your mistakes gently, and adjusts to your level automatically. Fifteen minutes a day with your morning coffee — that\'s all it takes.',
      agent1_tags: '<span>Real conversations</span><span>Gentle corrections</span><span>Daily habits</span>',
      agent2_label: 'Stars',
      agent2_title: 'Your Daily Astrology Reading',
      agent2_desc: 'Forget cookie-cutter horoscopes. Enter your birth details once, and PadClaw builds your complete natal chart. Every morning, you get a reading that\'s actually about you — your relationships, your career, your energy for the day.',
      agent2_tags: '<span>Personal chart</span><span>Morning readings</span><span>Relationship insights</span>',
      agent3_label: 'Weather',
      agent3_title: 'The Weather Report That Knows Your Life',
      agent3_desc: 'Most weather apps tell you the temperature. PadClaw tells you to bring an umbrella, skip the highway because of fog, and throw on a jacket for your kid\'s soccer game tonight. It reads your calendar, learns your routine, and delivers advice — not just data.',
      agent3_tags: '<span>Smart advice</span><span>Knows your schedule</span><span>Family-friendly</span>',
      agent4_label: 'Wellbeing',
      agent4_title: 'A Gentle Health Companion',
      agent4_desc: 'Dad\'s blood pressure medication at 8 AM. Mom\'s follow-up appointment next Tuesday. That nagging headache that\'s been going on for three days — should you see a doctor? PadClaw keeps track of it all and gives you honest, helpful guidance.',
      agent4_tags: '<span>Family reminders</span><span>Symptom check</span><span>Peace of mind</span>',
      s4_heading: 'And We\'re Just Getting Started',
      up1_label: 'Cook', up1_title: 'What\'s for Dinner Tonight?', up1_desc: 'Open the fridge, snap a photo. PadClaw sees what you have and suggests three meals you can make right now — with instructions your 12-year-old could follow.',
      up2_label: 'Bedtime', up2_title: 'Storytime That Never Repeats', up2_desc: 'Every night, a brand-new story starring the characters your child invents. They pick the setting, choose the plot twists, and hear it narrated aloud. Screen time you can feel good about.',
      up3_label: 'Money', up3_title: 'Know Where Your Money Goes', up3_desc: 'Say "I spent forty bucks on groceries" or snap a receipt. PadClaw tracks it, categorizes it, and shows you a monthly picture of your spending — without the spreadsheet headaches.',
      up4_label: 'Move', up4_title: 'A Coach Who Meets You Where You Are', up4_desc: 'Whether you\'re recovering from surgery or training for a 5K, the fitness assistant builds a plan around your body and your goals — then adjusts as you get stronger.',
      s5_heading: 'Everything You Need, Nothing You Don\'t',
      s5_body: '<p>Every PadClaw arrives ready to go:</p><ul class="feature-list"><li>PadClaw AI Tablet — beautiful 10.1" screen, 128GB storage</li><li>Protective case that doubles as a stand</li><li>USB-C cable and wall charger</li><li>Magnetic desktop stand (Early Bird and above) — perfect for the kitchen counter</li><li>Simple quick start card — you\'ll be up and running in two minutes</li><li>One full year of AI assistants included — no subscription for 12 months</li></ul>',
      s6_heading: 'Under the Hood',
      s7_heading: 'The People Behind PadClaw',
      s7_body: '<p>We\'re a small team in Taipei, Taiwan — engineers who build Android devices, designers who obsess over making technology feel human, and product people who listen more than they talk.</p><p>We started PadClaw because we watched our own parents struggle with AI tools that were built for Silicon Valley engineers. They deserve better. So does your family. We\'ve shipped real products before, we work with a factory we\'ve trusted for four years, and we\'re committed to getting this right.</p>',
      s8_heading: 'When It All Happens',
      s9_heading: 'Getting PadClaw to Your Door',
      s9_body: '<p>We want to be upfront so there are no surprises:</p><p><strong>Shipping costs are separate</strong> and will be collected after the campaign through a quick online survey. We\'re partnering with a US-based warehouse, so <strong>domestic US orders ship first and fastest.</strong></p><p>We ship internationally to most countries. We\'ll share estimated shipping costs for each region before the campaign ends, so you\'ll know exactly what to expect. Import duties and local taxes are handled by your local customs office — that\'s standard for any international purchase.</p>',
      s10_heading: 'Being Honest About What\'s Hard',
      s10_body: '<p>Building hardware is unpredictable. Components get delayed. Molds need revision. Firmware bugs surface at the worst possible time. We won\'t pretend otherwise.</p><p>What we will do is keep you in the loop — genuinely. Not with marketing-speak updates, but with real photos from the factory, real numbers, and real timelines. If something slips, you\'ll know why, and you\'ll know what we\'re doing about it.</p>',
      faq1_q: 'Do I have to pay extra for the AI assistants?', faq1_a: 'Nope — one full year of access is included with every PadClaw. After year one, there will be a small subscription for cloud features. We\'ll announce the price well before shipping.',
      faq2_q: 'Is PadClaw listening to me or collecting my data?', faq2_a: 'No. PadClaw processes personal data on the device itself. Nothing gets uploaded without your say-so. You can delete all your data anytime.',
      faq3_q: 'Can my kids use YouTube and Netflix on it?', faq3_a: 'Absolutely. PadClaw runs full Android, so all your favorite apps work — Google Play, streaming, games, everything.',
      faq4_q: 'How much will shipping cost?', faq4_a: 'Shipping is charged separately after the campaign. We\'ll post estimates for every region before the campaign ends so you can decide with full information.',
      faq5_q: 'Will you keep adding new assistants?', faq5_a: 'Yes — we have a full roadmap of new assistants coming after launch. As a Kickstarter backer, you get all new ones free during your included subscription year.',
      faq6_q: 'What if things get delayed?', faq6_a: 'We\'ve built extra time into our schedule and have backup suppliers ready. If something comes up, we\'ll tell you straight — with details, not excuses.',
      r1_title: 'Just Here to Help', r1_desc: 'A vote of confidence in what we\'re building. You\'ll receive a heartfelt thank-you and insider updates on our journey from prototype to your doorstep.',
      r2_title: 'Super Early Bird — Bring PadClaw Home', r2_desc: 'The best deal you\'ll ever find on PadClaw — 40% off the $999 retail price. One tablet, one case, one cable, and a full year of AI assistants. No subscriptions, no surprises for 12 months.',
      r3_title: 'Early Bird — The Complete Setup', r3_desc: '30% off retail. Everything in Super Early Bird plus a beautiful magnetic stand that props PadClaw up like a tiny family command center. Kitchen counter tested and approved.',
      r4_title: 'Kickstarter Special — Full Package', r4_desc: 'Still $200 less than the retail price. The complete PadClaw experience with stand and a full year of AI assistants. The perfect addition to any home.',
      r5_title: 'Family Pack — Two PadClaws', r5_desc: 'One for the kitchen, one for the grandparents. Two complete setups so the whole extended family stays connected, healthy, and a little more organized.',
      r6_title: 'Team Edition — Five PadClaws', r6_desc: 'Perfect for classrooms, senior care facilities, or small businesses. Five tablets, priority support, two years of AI access, and the option to customize which assistants appear on each device.',
    },
    zh: {
      title: 'PadClaw — 少一點切換，多一點生活',
      subtitle: '一台沉穩、always-on 的 AI 平板，把語言練習、健康提醒、每日預報和家庭協作集中在一起 — 專為廚房檯面、床頭櫃和生活中的每個時刻而生。',
      trust1: '首年使用權含在內 — 沒有意外費用',
      trust2: '你的對話保持私密',
      trust3: '同時也是一台完整 Android 平板',
      trust4: 'VIP 贊助者美國免運',
      s1_heading: '如果你的平板早就知道該做什麼呢？',
      s1_body: '<p>想像一下早上醒來，瞥一眼床頭的平板。它已經知道你的通勤路上會下雨，提醒你吃維他命。你女兒昨晚用它練習法語作業 — 而且居然樂在其中。</p><p>這就是 PadClaw。不是另一個需要你搞懂的小工具。不是另一個淹沒在通知海裡的 APP。它是你家的<strong>專屬 AI 夥伴</strong> — 預載了針對家人每天真正需要幫助的事情所設計的智慧助手。</p>',
      s2_heading: '為什麼不用手機就好？',
      s2_body: '<p>因為你的手機已經太忙了。簡訊、社群媒體、工作郵件、無盡滑動之間，已經沒有空間留給真正能幫到你的東西。</p><p>PadClaw 放在你的檯面、書桌、茶几上 — <strong>一個沉穩、專注的介面</strong>，隨時準備好為你服務。這就像把計時器埋在手機裡跟掛一個漂亮時鐘在牆上的差別。存在感很重要。專屬用途很重要。</p>',
      s2_features: '<li>拆箱、連 Wi-Fi、助手 60 秒內上線</li><li>每個助手都是為從未用過 AI 的人設計的</li><li>全家人都能用 — 不需要分開的帳號或登入</li><li>同時也是完整 Android 平板 — Netflix、YouTube、Kindle 都能用</li><li>個人資料留在裝置上 — 是你的，不是我們的</li><li>Always-on 螢幕代表助手在你開口前就已經準備好</li>',
      s3_heading: '為真實生活設計的內建助手',
      s3_intro: '每台 PadClaw 預載了圍繞日常時刻設計的 AI 助手：',
      agent1_label: '學習',
      agent1_title: '你的語言學伴',
      agent1_desc: '練語言不該像在寫作業。PadClaw 的語言助手跟你進行真實對話，溫和地糾正你的錯誤，自動調整到你的程度。每天早上咖啡時間 15 分鐘 — 就這麼簡單。',
      agent1_tags: '<span>真實對話</span><span>溫和糾正</span><span>每日習慣</span>',
      agent2_label: '星座',
      agent2_title: '你的每日星座解讀',
      agent2_desc: '忘掉那些千篇一律的星座運勢。輸入一次出生資料，PadClaw 建立你的完整本命盤。每天早上，你得到的是真正關於你的解讀 — 你的感情、你的事業、你今天的能量。',
      agent2_tags: '<span>個人星盤</span><span>晨間解讀</span><span>感情洞察</span>',
      agent3_label: '天氣',
      agent3_title: '懂你生活的天氣預報',
      agent3_desc: '一般天氣 APP 告訴你溫度。PadClaw 告訴你帶傘、因為霧避開高速公路、今晚孩子的足球賽記得多帶件外套。它讀你的行事曆、學你的作息，給你的是建議 — 不只是數據。',
      agent3_tags: '<span>聰明建議</span><span>知道你的行程</span><span>家庭友善</span>',
      agent4_label: '健康',
      agent4_title: '溫柔的健康夥伴',
      agent4_desc: '爸爸早上八點的血壓藥。媽媽下週二的回診。你那個已經頭痛三天的問題 — 該不該去看醫生？PadClaw 幫你追蹤一切，給你誠實、有用的建議。',
      agent4_tags: '<span>家庭提醒</span><span>症狀檢查</span><span>安心感</span>',
      s4_heading: '而這只是開始',
      up1_label: '煮飯', up1_title: '今晚吃什麼？', up1_desc: '打開冰箱拍張照。PadClaw 看到你有什麼，推薦三道你現在就能做的菜 — 你 12 歲的孩子都能跟著步驟做。',
      up2_label: '睡前', up2_title: '絕不重複的故事時間', up2_desc: '每晚一個全新故事，主角是孩子自己發明的角色。他們選場景、選劇情轉折，聽它朗讀出來。讓你安心的螢幕時間。',
      up3_label: '花費', up3_title: '知道錢花去哪', up3_desc: '說「我在超市花了四百」或拍一張收據。PadClaw 追蹤、分類，讓你看到每月花費全貌 — 不用開試算表。',
      up4_label: '運動', up4_title: '配合你狀態的教練', up4_desc: '不管你是手術恢復期還是在練 5 公里跑，健身助手會根據你的身體和目標制定計畫 — 然後隨你變強而調整。',
      s5_heading: '你需要的都有，不需要的都沒有',
      s5_body: '<p>每台 PadClaw 到手即可使用：</p><ul class="feature-list"><li>PadClaw AI 平板 — 漂亮的 10.1 吋螢幕、128GB 儲存</li><li>保護殼，可當立架用</li><li>USB-C 充電線和充電器</li><li>磁吸桌面立架（早鳥方案以上） — 放在廚房檯面剛好</li><li>簡單的快速入門卡 — 兩分鐘內上手</li><li>首年 AI 助手使用權含在內 — 12 個月不收訂閱費</li></ul>',
      s6_heading: '技術規格',
      s7_heading: 'PadClaw 背後的人',
      s7_body: '<p>我們是台北的一支小團隊 — 做 Android 裝置的工程師、執著於讓科技有人味的設計師、以及聽得比說得多的產品人。</p><p>我們做 PadClaw，是因為我們看著自己的爸媽在那些為矽谷工程師設計的 AI 工具前手足無措。他們值得更好的。你的家人也是。我們出過真正的產品，和一間信任四年的工廠合作，而且我們決心把這件事做對。</p>',
      s8_heading: '一切什麼時候發生',
      s9_heading: '把 PadClaw 送到你家門口',
      s9_body: '<p>我們想提前說清楚，不要有意外：</p><p><strong>運費另計</strong>，會在募資結束後透過簡單的線上問卷收取。我們與美國在地倉庫合作，所以<strong>美國國內訂單優先且最快出貨。</strong></p><p>我們配送到大多數國家。募資結束前會公布各地區的預估運費，讓你清楚知道預期花費。進口關稅和當地稅金由你的當地海關處理 — 這是任何國際購買的標準流程。</p>',
      s10_heading: '誠實面對困難的部分',
      s10_body: '<p>做硬體充滿變數。零件延遲、模具要修、韌體 bug 總在最糟的時候冒出來。我們不會假裝這些不存在。</p><p>我們會做的是真正讓你掌握狀況。不是行銷語言的更新，而是工廠的真實照片、真實數據和真實時程。如果有什麼延遲，你會知道為什麼，也會知道我們正在做什麼。</p>',
      faq1_q: 'AI 助手要另外付費嗎？', faq1_a: '不用 — 每台 PadClaw 含首年完整使用權。第一年後雲端功能會有小額訂閱費。定價會在出貨前就公布。',
      faq2_q: 'PadClaw 會監聽我或蒐集我的資料嗎？', faq2_a: '不會。PadClaw 在裝置本身處理個人資料。未經你同意不會上傳任何東西。你可以隨時刪除所有資料。',
      faq3_q: '小孩可以在上面看 YouTube 和 Netflix 嗎？', faq3_a: '當然。PadClaw 跑完整 Android，所有你愛的 APP 都能用 — Google Play、串流、遊戲，全部。',
      faq4_q: '運費要多少？', faq4_a: '運費在募資結束後另行收取。我們會在募資關閉前公布各地區預估費用，讓你有完整資訊做決定。',
      faq5_q: '之後會繼續加新助手嗎？', faq5_a: '會 — 我們有完整的新助手路線圖。身為 Kickstarter 贊助者，你在首年訂閱期間內免費取得所有新助手。',
      faq6_q: '如果延遲了怎麼辦？', faq6_a: '我們在時程裡預留了額外時間，備援供應商也已就緒。如果有狀況，我們會直說 — 附上細節，不是藉口。',
      r1_title: '純粹支持', r1_desc: '對我們正在做的事投一票信任。你會收到一封真心感謝信，以及從原型到送到你家門口的旅程內幕更新。',
      r2_title: '超級早鳥 — 把 PadClaw 帶回家', r2_desc: 'PadClaw 最划算的價格 — 零售價 $999 的 6 折。一台平板、一個保護殼、一條充電線，加上一整年的 AI 助手。12 個月不收訂閱費、不會有意外。',
      r3_title: '早鳥 — 完整配置', r3_desc: '零售價 7 折。包含超級早鳥的所有內容，再加一個漂亮的磁吸立架，把 PadClaw 變成家裡的小型指揮中心。廚房檯面實測通過。',
      r4_title: 'Kickstarter 限定 — 完整套裝', r4_desc: '仍比零售價便宜 $200。完整 PadClaw 體驗，含立架與首年 AI 助手。任何家庭的完美新成員。',
      r5_title: '家庭組 — 兩台 PadClaw', r5_desc: '一台放廚房、一台給阿公阿嬤。兩套完整配置，讓全家保持連結、健康，而且稍微更有條理一點。',
      r6_title: '團隊版 — 五台 PadClaw', r6_desc: '適合教室、長照機構或小型企業。五台平板、優先客服、兩年 AI 使用權，以及自訂每台裝置顯示哪些助手的選項。',
    },
  },
},

];
